// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AssessmentConfirm: typeof import('./components/tests/AssessmentConfirm.vue')['default']
    AssessmentResults: typeof import('./components/tests/AssessmentResults.vue')['default']
    BehaviouralAssessment: typeof import('./components/tests/BehaviouralAssessment.vue')['default']
    BiologicalAssessment: typeof import('./components/tests/BiologicalAssessment.vue')['default']
    BiometricAssessment: typeof import('./components/tests/BiometricAssessment.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    ElAvatar: typeof import('element-plus/lib')['ElAvatar']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCard: typeof import('element-plus/lib')['ElCard']
    ElCollapse: typeof import('element-plus/lib')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/lib')['ElCollapseItem']
    ElDialog: typeof import('element-plus/lib')['ElDialog']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElProgress: typeof import('element-plus/lib')['ElProgress']
    ElSelectV2: typeof import('element-plus/lib')['ElSelectV2']
    ElTabPane: typeof import('element-plus/lib')['ElTabPane']
    ElTabs: typeof import('element-plus/lib')['ElTabs']
    Footer: typeof import('./components/Footer.vue')['default']
    GlassCard: typeof import('./components/ui/GlassCard.vue')['default']
    InfoAccordion: typeof import('./components/learn/InfoAccordion.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/nav/TopBar.vue')['default']
  }
}

export {}
