// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    ElAvatar: typeof import('element-plus/lib')['ElAvatar']
    Footer: typeof import('./components/Footer.vue')['default']
    GlassCard: typeof import('./components/ui/GlassCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/nav/TopBar.vue')['default']
  }
}

export {}
